// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "gin-demo/internal/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// INewsLogRepository is an autogenerated mock type for the INewsLogRepository type
type INewsLogRepository struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: tx, log
func (_m *INewsLogRepository) CreateTx(tx *gorm.DB, log *model.NewsLog) error {
	ret := _m.Called(tx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.NewsLog) error); ok {
		r0 = rf(tx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINewsLogRepository creates a new instance of INewsLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewsLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewsLogRepository {
	mock := &INewsLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
