// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "gin-demo/internal/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// INewsRepository is an autogenerated mock type for the INewsRepository type
type INewsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: news
func (_m *INewsRepository) Create(news *model.News) error {
	ret := _m.Called(news)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.News) error); ok {
		r0 = rf(news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTx provides a mock function with given fields: tx, news
func (_m *INewsRepository) CreateTx(tx *gorm.DB, news *model.News) error {
	ret := _m.Called(tx, news)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.News) error); ok {
		r0 = rf(tx, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *INewsRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *INewsRepository) FindAll() ([]model.News, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.News
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.News, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.News); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.News)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *INewsRepository) FindByID(id uint) (*model.News, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.News
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.News, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.News); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.News)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPaged provides a mock function with given fields: page, size, status
func (_m *INewsRepository) FindPaged(page int, size int, status *int) ([]model.News, int64) {
	ret := _m.Called(page, size, status)

	if len(ret) == 0 {
		panic("no return value specified for FindPaged")
	}

	var r0 []model.News
	var r1 int64
	if rf, ok := ret.Get(0).(func(int, int, *int) ([]model.News, int64)); ok {
		return rf(page, size, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, *int) []model.News); ok {
		r0 = rf(page, size, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.News)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, *int) int64); ok {
		r1 = rf(page, size, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// Transaction provides a mock function with given fields: fn
func (_m *INewsRepository) Transaction(fn func(*gorm.DB) error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*gorm.DB) error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: news
func (_m *INewsRepository) Update(news *model.News) error {
	ret := _m.Called(news)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.News) error); ok {
		r0 = rf(news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINewsRepository creates a new instance of INewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewsRepository {
	mock := &INewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
